-- =====================================================
-- EXTENSÃO DAS DIMENSÕES PARA CONTROLE DE ESTOQUE
-- =====================================================

USE SCHEMA DWH;

-- Dimensão de Depósitos/Armazéns (surrogate key)
CREATE OR REPLACE TABLE DIM_WAREHOUSE (
  WAREHOUSE_SK NUMBER IDENTITY PRIMARY KEY,
  WAREHOUSE_ID VARCHAR UNIQUE,
  WAREHOUSE_NAME VARCHAR,
  LOCATION VARCHAR,
  WAREHOUSE_TYPE VARCHAR,
  STATE VARCHAR, -- Extraído da LOCATION
  CREATED_AT TIMESTAMP
);

INSERT INTO DIM_WAREHOUSE (WAREHOUSE_ID, WAREHOUSE_NAME, LOCATION, WAREHOUSE_TYPE, STATE, CREATED_AT)
SELECT 
  WAREHOUSE_ID,
  WAREHOUSE_NAME,
  LOCATION,
  WAREHOUSE_TYPE,
  CASE 
    WHEN LOCATION LIKE '%SP%' THEN 'SP'
    WHEN LOCATION LIKE '%RJ%' THEN 'RJ'
    WHEN LOCATION LIKE '%MG%' THEN 'MG'
    ELSE 'OUTROS'
  END AS STATE,
  CREATED_AT
FROM STAGING.WAREHOUSES;

-- Dimensão de Fornecedores (surrogate key)
CREATE OR REPLACE TABLE DIM_SUPPLIER (
  SUPPLIER_SK NUMBER IDENTITY PRIMARY KEY,
  SUPPLIER_ID VARCHAR UNIQUE,
  SUPPLIER_NAME VARCHAR,
  CONTACT_EMAIL VARCHAR,
  STATE VARCHAR,
  CREATED_AT TIMESTAMP
);

INSERT INTO DIM_SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, CONTACT_EMAIL, STATE, CREATED_AT)
SELECT SUPPLIER_ID, SUPPLIER_NAME, CONTACT_EMAIL, STATE, CREATED_AT
FROM STAGING.SUPPLIERS;

-- Dimensão de Tipo de Movimentação (dimensão degenerada expandida)
CREATE OR REPLACE TABLE DIM_MOVEMENT_TYPE (
  MOVEMENT_TYPE_SK NUMBER IDENTITY PRIMARY KEY,
  MOVEMENT_TYPE VARCHAR UNIQUE,
  MOVEMENT_CATEGORY VARCHAR, -- 'IN', 'OUT', 'ADJUSTMENT'
  DESCRIPTION VARCHAR,
  AFFECTS_STOCK BOOLEAN
);

INSERT INTO DIM_MOVEMENT_TYPE (MOVEMENT_TYPE, MOVEMENT_CATEGORY, DESCRIPTION, AFFECTS_STOCK) VALUES
('PURCHASE', 'IN', 'Compra de fornecedor', TRUE),
('SALE', 'OUT', 'Venda para cliente', TRUE),
('ADJUSTMENT', 'ADJUSTMENT', 'Ajuste de inventário', TRUE),
('TRANSFER_IN', 'IN', 'Transferência recebida', TRUE),
('TRANSFER_OUT', 'OUT', 'Transferência enviada', TRUE),
('DAMAGE', 'OUT', 'Perda por dano', TRUE),
('THEFT', 'OUT', 'Perda por roubo', TRUE),
('RETURN', 'IN', 'Devolução de cliente', TRUE); 