USE SCHEMA CORE;

-- Dimensão de datas (YYYYMMDD como chave)
CREATE OR REPLACE TABLE DIM_DATE (
  DATE_KEY    INT PRIMARY KEY,     -- yyyymmdd
  DDATE       DATE,
  YEAR        INT,
  QUARTER     INT,
  MONTH       INT,
  DAY         INT,
  DOW_ISO     INT,
  IS_WEEKEND  BOOLEAN
);

-- Povoar 2023-2025 (ajuste o range conforme necessidade)
INSERT INTO DIM_DATE
SELECT
    TO_NUMBER(TO_VARCHAR(d, 'YYYYMMDD'))       AS DATE_KEY,
    d                                          AS DDATE,
    YEAR(d)                                    AS YEAR,
    QUARTER(d)                                 AS QUARTER,
    MONTH(d)                                   AS MONTH,
    DAY(d)                                     AS DAY,
    DAYOFWEEKISO(d)                            AS DOW_ISO,
    (DAYOFWEEKISO(d) IN (6,7))                 AS IS_WEEKEND
FROM (
    SELECT DATEADD('day', SEQ4(), '2023-01-01') AS d
    FROM TABLE(GENERATOR(ROWCOUNT => 365*3))
);

-- Dimensão de clientes (surrogate key)
CREATE OR REPLACE TABLE DIM_CUSTOMER (
  CUSTOMER_SK NUMBER IDENTITY PRIMARY KEY,
  CUSTOMER_ID VARCHAR UNIQUE,
  FULL_NAME   VARCHAR,
  EMAIL       VARCHAR,
  STATE       VARCHAR,
  CREATED_AT  TIMESTAMP
);

INSERT INTO DIM_CUSTOMER (CUSTOMER_ID, FULL_NAME, EMAIL, STATE, CREATED_AT)
SELECT CUSTOMER_ID, FULL_NAME, EMAIL, STATE, CREATED_AT
FROM STAGING.CUSTOMERS;

-- Dimensão de produtos (surrogate key)
CREATE OR REPLACE TABLE DIM_PRODUCT (
  PRODUCT_SK NUMBER IDENTITY PRIMARY KEY,
  SKU        VARCHAR UNIQUE,
  PRODUCT    VARCHAR,
  CATEGORY   VARCHAR,
  PRICE      NUMBER(12,2)
);

INSERT INTO DIM_PRODUCT (SKU, PRODUCT, CATEGORY, PRICE)
SELECT SKU, PRODUCT, CATEGORY, PRICE
FROM STAGING.PRODUCTS;

-- Dimensão de pedidos (surrogate key)
CREATE OR REPLACE TABLE DIM_ORDER (
  ORDER_SK    NUMBER IDENTITY PRIMARY KEY,
  ORDER_ID    VARCHAR UNIQUE,
  ORDER_TS    TIMESTAMP,
  TOTAL_AMOUNT NUMBER(12,2),
  TAX_AMOUNT   NUMBER(12,2),
  CUSTOMER_ID  VARCHAR  -- Para facilitar JOINs (desnormalização controlada)
);

INSERT INTO DIM_ORDER (ORDER_ID, ORDER_TS, TOTAL_AMOUNT, TAX_AMOUNT, CUSTOMER_ID)
SELECT ORDER_ID, ORDER_TS, TOTAL_AMOUNT, TAX_AMOUNT, CUSTOMER_ID
FROM STAGING.ORDERS;
