CREATE OR REPLACE TABLE FACT_SALES (
  ORDER_ID     VARCHAR,
  ORDER_ITEM   INT,
  DATE_KEY     INT           REFERENCES DIM_DATE(DATE_KEY),
  CUSTOMER_SK  NUMBER        REFERENCES DIM_CUSTOMER(CUSTOMER_SK),
  PRODUCT_SK   NUMBER        REFERENCES DIM_PRODUCT(PRODUCT_SK),
  QUANTITY     INT,
  UNIT_PRICE   NUMBER(12,2),
  GROSS_AMOUNT NUMBER(12,2),
  PRIMARY KEY (ORDER_ID, ORDER_ITEM)
);

INSERT INTO FACT_SALES (
  ORDER_ID, ORDER_ITEM, DATE_KEY, CUSTOMER_SK, PRODUCT_SK, QUANTITY, UNIT_PRICE, GROSS_AMOUNT
)
SELECT
  o.ORDER_ID,
  o.ORDER_ITEM,
  TO_NUMBER(TO_VARCHAR(CAST(o.ORDER_TS AS DATE), 'YYYYMMDD')) AS DATE_KEY,
  dc.CUSTOMER_SK,
  dp.PRODUCT_SK,
  o.QUANTITY,
  o.UNIT_PRICE,
  o.QUANTITY * o.UNIT_PRICE AS GROSS_AMOUNT
FROM STAGING.ORDERS o
JOIN DIM_CUSTOMER dc ON dc.CUSTOMER_ID = o.CUSTOMER_ID
JOIN DIM_PRODUCT  dp ON dp.SKU        = o.SKU;
