CREATE OR REPLACE TABLE FACT_SALES (
  ORDER_ID     VARCHAR,
  ORDER_ITEM   INT,
  DATE_KEY     INT           REFERENCES DIM_DATE(DATE_KEY),
  CUSTOMER_SK  NUMBER        REFERENCES DIM_CUSTOMER(CUSTOMER_SK),
  PRODUCT_SK   NUMBER        REFERENCES DIM_PRODUCT(PRODUCT_SK),
  ORDER_SK     NUMBER        REFERENCES DIM_ORDER(ORDER_SK),
  QUANTITY     INT,
  UNIT_PRICE   NUMBER(12,2),
  GROSS_AMOUNT NUMBER(12,2),
  PRIMARY KEY (ORDER_ID, ORDER_ITEM)
);

INSERT INTO FACT_SALES (
  ORDER_ID, ORDER_ITEM, DATE_KEY, CUSTOMER_SK, PRODUCT_SK, ORDER_SK, QUANTITY, UNIT_PRICE, GROSS_AMOUNT
)
SELECT
  oi.ORDER_ID,
  oi.ORDER_ITEM,
  TO_NUMBER(TO_VARCHAR(CAST(do.ORDER_TS AS DATE), 'YYYYMMDD')) AS DATE_KEY,
  dc.CUSTOMER_SK,
  dp.PRODUCT_SK,
  do.ORDER_SK,
  oi.QUANTITY,
  oi.UNIT_PRICE,
  oi.QUANTITY * oi.UNIT_PRICE AS GROSS_AMOUNT
FROM STAGING.ORDER_ITEMS oi
JOIN DIM_ORDER do ON do.ORDER_ID = oi.ORDER_ID
JOIN DIM_CUSTOMER dc ON dc.CUSTOMER_ID = do.CUSTOMER_ID
JOIN DIM_PRODUCT  dp ON dp.SKU = oi.SKU;
