-- =====================================================================
-- METABASE INTEGRATION
-- =====================================================================
CREATE WAREHOUSE IF NOT EXISTS LAB_WH_METABASE
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE LAB_WH_METABASE;

CREATE DATABASE IF NOT EXISTS LAB_PIPELINE;
USE DATABASE LAB_PIPELINE;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS CORE;
CREATE ROLE METABASE_DEV;

CREATE USER METABASE_DEV
  DEFAULT_ROLE = METABASE_DEV
  DEFAULT_WAREHOUSE = LAB_WH_METABASE
  DEFAULT_NAMESPACE = LAB_PIPELINE.PUBLIC
  PASSWORD = 'mudar@123';

GRANT ROLE METABASE_DEV TO USER METABASE_DEV;

-- Use of the warehouse, database and schema
GRANT USAGE ON WAREHOUSE LAB_WH_METABASE TO ROLE METABASE_DEV;
GRANT OPERATE ON WAREHOUSE LAB_WH_METABASE TO ROLE METABASE_DEV;
GRANT USAGE ON DATABASE LAB_PIPELINE TO ROLE METABASE_DEV;
GRANT USAGE ON SCHEMA LAB_PIPELINE.PUBLIC TO ROLE METABASE_DEV;
GRANT USAGE ON SCHEMA LAB_PIPELINE.STAGING TO ROLE METABASE_DEV;
GRANT USAGE ON SCHEMA LAB_PIPELINE.CORE TO ROLE METABASE_DEV;

-- To access to tables
GRANT SELECT ON ALL TABLES IN SCHEMA LAB_PIPELINE.PUBLIC TO ROLE METABASE_DEV;
GRANT SELECT ON FUTURE TABLES IN SCHEMA LAB_PIPELINE.PUBLIC TO ROLE METABASE_DEV;

GRANT SELECT ON ALL TABLES IN SCHEMA LAB_PIPELINE.STAGING TO ROLE METABASE_DEV;
GRANT SELECT ON FUTURE TABLES IN SCHEMA LAB_PIPELINE.STAGING TO ROLE METABASE_DEV;

GRANT SELECT ON ALL TABLES IN SCHEMA LAB_PIPELINE.CORE TO ROLE METABASE_DEV;
GRANT SELECT ON FUTURE TABLES IN SCHEMA LAB_PIPELINE.CORE TO ROLE METABASE_DEV;
