-- =====================================================================
-- DBT INTEGRATION
-- =====================================================================
CREATE WAREHOUSE IF NOT EXISTS LAB_WH_DBT
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE LAB_WH_DBT;

CREATE DATABASE IF NOT EXISTS LAB_PIPELINE;
USE DATABASE LAB_PIPELINE;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS CORE;
CREATE ROLE DBT_DEV;

CREATE USER DBT_DEV
  DEFAULT_ROLE = DBT_DEV
  DEFAULT_WAREHOUSE = LAB_WH_DBT
  DEFAULT_NAMESPACE = LAB_PIPELINE.PUBLIC
  PASSWORD = 'mudar@123';

GRANT ROLE DBT_DEV TO USER DBT_DEV;

-- Use of the warehouse, database and schema
GRANT USAGE ON WAREHOUSE LAB_WH_DBT TO ROLE DBT_DEV;
GRANT OPERATE ON WAREHOUSE LAB_WH_DBT TO ROLE DBT_DEV;
GRANT USAGE ON DATABASE LAB_PIPELINE TO ROLE DBT_DEV;
GRANT USAGE ON SCHEMA LAB_PIPELINE.PUBLIC TO ROLE DBT_DEV;
GRANT USAGE ON SCHEMA LAB_PIPELINE.STAGING TO ROLE DBT_DEV;
GRANT USAGE ON SCHEMA LAB_PIPELINE.CORE TO ROLE DBT_DEV;

-- To access to tables
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA LAB_PIPELINE.PUBLIC TO ROLE DBT_DEV;
GRANT SELECT, UPDATE, INSERT, DELETE ON FUTURE TABLES IN SCHEMA LAB_PIPELINE.PUBLIC TO ROLE DBT_DEV;

GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA LAB_PIPELINE.STAGING TO ROLE DBT_DEV;
GRANT SELECT, UPDATE, INSERT, DELETE ON FUTURE TABLES IN SCHEMA LAB_PIPELINE.STAGING TO ROLE DBT_DEV;

GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA LAB_PIPELINE.CORE TO ROLE DBT_DEV;
GRANT SELECT, UPDATE, INSERT, DELETE ON FUTURE TABLES IN SCHEMA LAB_PIPELINE.CORE TO ROLE DBT_DEV;

-- To create schemas and tables
GRANT CREATE SCHEMA ON DATABASE LAB_PIPELINE TO ROLE DBT_DEV;
GRANT CREATE TABLE ON SCHEMA LAB_PIPELINE.PUBLIC TO ROLE DBT_DEV;
GRANT CREATE FUNCTION ON SCHEMA LAB_PIPELINE.PUBLIC TO ROLE DBT_DEV;

GRANT CREATE TABLE ON SCHEMA LAB_PIPELINE.STAGING TO ROLE DBT_DEV;
GRANT CREATE FUNCTION ON SCHEMA LAB_PIPELINE.STAGING TO ROLE DBT_DEV;

GRANT CREATE TABLE ON SCHEMA LAB_PIPELINE.CORE TO ROLE DBT_DEV;
GRANT CREATE FUNCTION ON SCHEMA LAB_PIPELINE.CORE TO ROLE DBT_DEV;
