-- 0 órfãos: fato deve ter chaves válidas nas dimensões
SELECT COUNT(*) AS ORFAOS_CUSTOMER
FROM FACT_SALES f LEFT JOIN DIM_CUSTOMER d ON d.CUSTOMER_SK = f.CUSTOMER_SK
WHERE d.CUSTOMER_SK IS NULL;

SELECT COUNT(*) AS ORFAOS_PRODUCT
FROM FACT_SALES f LEFT JOIN DIM_PRODUCT d ON d.PRODUCT_SK = f.PRODUCT_SK
WHERE d.PRODUCT_SK IS NULL;

-- Reconciliação de receita
SELECT SUM(QUANTITY * UNIT_PRICE) AS RECEITA_STAGING FROM STAGING.ORDERS;
SELECT SUM(GROSS_AMOUNT)          AS RECEITA_FATO    FROM FACT_SALES;

-- Unicidade do grain
SELECT ORDER_ID, ORDER_ITEM, COUNT(*) CNT
FROM FACT_SALES GROUP BY 1,2 HAVING COUNT(*) > 1;

-- Distribuição diária
SELECT d.DDATE, SUM(GROSS_AMOUNT) AS RECEITA_DIA
FROM FACT_SALES f
JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
GROUP BY 1 ORDER BY 1;
